[project]
name = 'Tokenized-Specialized-Film-Visual-Effects-Rights'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.studio-verification]
path = 'contracts/studio-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
